ORDER_NOT_CHARGED = "Order was not charged."
INVALID_REQUEST = "El pago fue denegado."
SERVER_ERROR = "No se pudo procesar su orden."
UNSUPPORTED_CURRENCY = "La moneda %(currency)s no es valida."
MP_ERROR = "Ocurrió un error con la aplicación de Mercado Pago."

STATUS_DETAIL = {
    "accredited": "¡Listo! Se acreditó tu pago. En tu resumen verás el cargo de amount como statement_descriptor",
    "cc_rejected_bad_filled_card_number": "Revisa el número de tarjeta.",
    "cc_rejected_bad_filled_date": "Revisa la fecha de vencimiento.",
    "cc_rejected_bad_filled_other": "Revisa los datos.",
    "cc_rejected_bad_filled_security_code":	"Revisa el código de seguridad de la tarjeta.",
    "cc_rejected_blacklist": "No pudimos procesar tu pago.",
    "cc_rejected_call_for_authorize": "Debes autorizar ante payment_method_id el pago de amount.",
    "cc_rejected_card_disabled": "Llama a payment_method_id para activar tu tarjeta o usa otro medio de pago.",
    "cc_rejected_card_error": "No pudimos procesar tu pago.",
    "cc_rejected_duplicated_payment": "Ya hiciste un pago por ese valor. Si necesitas volver a pagar usa otra tarjeta u otro medio de pago.",
    "cc_rejected_high_risk": "Tu pago fue rechazado. Elige otro de los medios de pago, te recomendamos con medios en efectivo.",
    "cc_rejected_insufficient_amount": "Tu payment_method_id no tiene fondos suficientes.",
    "cc_rejected_invalid_installments": "payment_method_id no procesa pagos en installments cuotas.",
    "cc_rejected_max_attempts": "Llegaste al límite de intentos permitidos. Elige otra tarjeta u otro medio de pago.",
    "cc_rejected_other_reason":	"payment_method_id no procesó el pago.",
    "pending_contingency": "Estamos procesando tu pago. No te preocupes, menos de 2 días hábiles te avisaremos por e-mail si se acreditó.",
	"pending_review_manual": "Estamos procesando tu pago. No te preocupes, menos de 2 días hábiles te avisaremos por e-mail si se acreditó o si necesitamos más información.",
}

MP_API_ERROR = {
    1: "Error de parámetros.",
    3: "El token debe ser para test.",
    4: "El usuario no esta autorizado a acceder a este recurso.",
    5: "Debes proveer tu access_token para proceder.",
    23: "El siguiente parámetro debe ser una fecha válida en formato (yyyy-MM-dd'T'HH:mm:ssz) date_of_expiration.",
    1000: "El número de filas excede los límites.",
    1001: "El formato de fecha debe ser yyyy-MM-dd'T'HH:mm:ss.SSSZ.",
    2000: "No se ha encontrado el pago.",
    2001: "Ya se posteó el mismo request en el último minuto.",
    2004: "Falló el POST a Gateway Transactions API.",
    2002: "Cliente no encontrado.",
    2006: "Card Token no encontrado.",
    2007: "Falló la conexión a Card Token API.",
    2009: "Card token issuer no puede ser nulo.",
    2034: "Usuario invalido",
    2060: "El cliente no puede ser igual al vendedor.",
    3000: "Debes proveer el parámetro cardholder_name en card data.",
    3001: "Debes proveer el parámetro cardholder_name en card data.",
    3002: "El usuario no está autorizado a realizar esta acción.",
    3003: "card_token_id inválido.",
    3004: "parameter site_id inválido.",
    3005: "Acción inválida, el recurso esta en un estado que no permite esta operación. Para más información consulta el estado del recurso.",
    3006: "cardtoken_id inválido.",
    3007: "El parámetro client_id no puede ser nulo ni vacío.",
    3008: "Cardtoken no encontrado.",
    3009: "client_id no autorizado.",
    3010: "La tarjeta no se encuentra en la lista blanca.",
    3011: "payment_method no encontrado.",
    3012: "security_code_length inválido.",
    3013: "El parámetro security_code es requerido y no puede ser nulo ni vacío.",
    3014: "payment_method inválido.",
    3015: "card_number_length inválido.",
    3016: "card_number inválido.",
    3017: "El parámetro card_number_id no puede ser nulo ni vacío.",
    3018: "El parámetro expiration_month no puede ser nulo ni vacío.",
    3019: "El parámetro expiration_year no puede ser nulo ni vacío.",
    3020: "El parámetro cardholder.name no puede ser nulo ni vacío.",
    3021: "El parámetro cardholder.document.number no puede ser nulo ni vacío.",
    3022: "El parámetro cardholder.document.type no puede ser nulo ni vacío.",
    3023: "El parámetro cardholder.document.subtype no puede ser nulo ni vacío.",
    3024: "Acción inválida, reembolsos parciales no soportados para esta transacción.",
    3025: "Código de autorización inválido.",
    3026: "card_id inválido para este payment_method_id.",
    3027: "payment_type_id inválido.",
    3028: "payment_method_id inválido.",
    3029: "Mes de expiración de tarjeta inválido.",
    3030: "Año de expiración de tarjeta inválido.",
    4000: "El parámetro card no puede ser nulo.",
    4001: "payment_method_id no puede ser nulo.",
    4002: "transaction_amount no puede ser nulo.",
    4003: "transaction_amount debe ser numérico",
    4004: "installments no puede ser nulo.",
    4005: "installments debe ser numérico.",
    4006: "payer está mal formado.",
    4007: "site_id no puede ser nulo.",
    4012: "payer.id no puede ser nulo.",
    4013: "payer.type no puede ser nulo.",
    4015: "payment_method_reference_id no puede ser nulo.",
    4016: "payment_method_reference_id debe ser numérico.",
    4017: "status no puede ser nulo.",
    4018: "payment_id no puede ser nulo.",
    4019: "payment_id debe ser numérico.",
    4020: "notificaction_url debe ser una url válida.",
    4021: "notificaction_url debe tener una longitud menor a 500 caracteres.",
    4022: "metadata debe ser un JSON válido.",
    4023: "transaction_amount no puede ser nulo.",
    4024: "transaction_amount debe ser numérico.",
    4025: "refund_id no puede ser nulo.",
    4026: "coupon_amount inválido.",
    4027: "campaign_id debe ser numérico.",
    4028: "coupon_amount atributte debe ser numérico.",
    4029: "Tipo de payer inválido.",
    4037: "transaction_amount inválido.",
    4038: "application_fee no puede ser mayor que transaction_amount.",
    4039: "application_fee no puede ser un valor negativo.",
    4050: "payer.email debe ser un email válido.",
    4051: "La longitud de payer.email debe ser menor que 254 caracteres.",
    7523: "Fecha de expiración inválida.",
}