# Generated by Django 3.1.2 on 2021-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20201104_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_status',
            field=models.CharField(choices=[('not-charged', 'Sin Pagar'), ('pending', 'Pendiente'), ('partially-charged', 'Parcialmente Pagada'), ('fully-charged', 'Pagada'), ('partially-refunded', 'Parcialmente Reembolsada'), ('fully-refunded', 'Reembolsada'), ('refused', 'Rechazada'), ('cancelled', 'Cancelada')], default='not-charged', max_length=20),
        ),
    ]
