# Generated by Django 3.1.2 on 2021-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_auto_20201108_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('fulfilled', 'Cumplida'), ('canceled', 'Cancelada')], default='fulfilled', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('unfulfilled', 'Incumplida'), ('partially fulfilled', 'Parcialmente Cumplida'), ('fulfilled', 'Cumplida'), ('canceled', 'Cancelada')], default='unfulfilled', max_length=32),
        ),
    ]
