# Generated by Django 3.1.2 on 2021-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_auto_20210107_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_external_id',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
