# Generated by Django 3.1.2 on 2021-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_order_gateway_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gateway_external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
